# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23b8d40bcd0a229a85cafca61e6b0c2634efdf827085bb1eacad0fe7d1135c219e49aacaaf7975b33006db36c2b4bd7e8b4f4f0098c5f4d15aa207a43b737087

test:
  secret_key_base: 2bc2137578666871feecb8a9a34674fed61511b89ac22325bb94273dedbc57860fcb6bd0658ac70b602b18c20018a6bbc9676c3c755acc6135e310bda4feb8a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
